//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spelers_champions
    {
        public int id { get; set; }
        public string Naam { get; set; }
        public int LevelMastery { get; set; }
        public string FreeToPlay { get; set; }
        public Nullable<int> SpelerId { get; set; }
        public Nullable<int> ChampionsId { get; set; }
    
        public virtual Champions Champions { get; set; }
        public virtual Speler Speler { get; set; }
    }
}
