//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spelers_Skin
    {
        public int id { get; set; }
        public string Naam { get; set; }
        public Nullable<int> SkinsId { get; set; }
        public Nullable<int> SpelerId { get; set; }
    
        public virtual Skin Skins { get; set; }
        public virtual Speler Speler { get; set; }
    }
}
